imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    version: 1.10.5

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    assets:
        version: '%version%'
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    #debug:            "%kernel.debug%"
    debug: true
    strict_variables: "%kernel.debug%"
    form_themes:
        - AppBundle:Form:aaplus-bootstrap.html.twig
        - AppBundle:Form:form_div_layout.html.twig
    date:
        format: Y-m-d
    number_format:
        decimals: 2
        decimal_point: ','
        thousands_separator: '.'
    globals:
        aaplus_release_ver: 'Release %version%'
        baseline_graddage_url: https://www.dmi.dk/vejrarkiv/maneden-sasonen-og-arets-vejr/tabeller-maaned/
        footer:
          name: '%app.page_footer.name%'
          address: '%app.page_footer.address%'
          email: '%app.page_footer.email%'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        server_version: "%server_version%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        mapping_types:
            enum: string
        types:
            LevetidType: AppBundle\DBAL\Types\LevetidType
            CardinalDirectionType: AppBundle\DBAL\Types\CardinalDirectionType
            NavnType: AppBundle\DBAL\Types\Energiforsyning\NavnType
            PrisgrundlagType: AppBundle\DBAL\Types\Energiforsyning\InternProduktion\PrisgrundlagType
            BygningStatusType: AppBundle\DBAL\Types\BygningStatusType
            StyringType: AppBundle\DBAL\Types\BelysningTiltagDetail\StyringType
            TiltagType: AppBundle\DBAL\Types\BelysningTiltagDetail\TiltagType
            PlaceringType: AppBundle\DBAL\Types\BelysningTiltagDetail\PlaceringType
            ArealKildePrimaerType: AppBundle\DBAL\Types\Baseline\ArealKildePrimaerType
            ArealKildeSekundaerType: AppBundle\DBAL\Types\Baseline\ArealKildeSekundaerType
            ElKildePrimaerType: AppBundle\DBAL\Types\Baseline\ElKildePrimaerType
            ElKildeSekundaerType: AppBundle\DBAL\Types\Baseline\ElKildeSekundaerType
            VarmeKildePrimaerType: AppBundle\DBAL\Types\Baseline\VarmeKildePrimaerType
            VarmeKildeSekundaerType: AppBundle\DBAL\Types\Baseline\VarmeKildeSekundaerType
            GUFFastsaettesEfterType: AppBundle\DBAL\Types\Baseline\GUFFastsaettesEfterType
            RisikovurderingType: AppBundle\DBAL\Types\RisikovurderingType
            PrimaerEnterpriseType: AppBundle\DBAL\Types\PrimaerEnterpriseType
            KlimaskaermType: AppBundle\DBAL\Types\KlimaskaermType
            VirksomhedTypeType: AppBundle\DBAL\Types\VirksomhedTypeType
            SlutanvendelseType: AppBundle\DBAL\Types\SlutanvendelseType
            ContactPersonReferenceType: AppBundle\DBAL\Types\ContactPersonReferenceType
        logging: false
        profiling: false
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
              auto_mapping: true
              dql:
                datetime_functions:
                  YEAR: DoctrineExtensions\Query\Mysql\Year

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# app/config/config.yml
braincrafted_bootstrap:
    icon_prefix: fa
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/components/jquery/jquery.min.js
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: false
        twig: false
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    group:
        group_class: AppBundle\Entity\Group
    profile:
        form:
            type: appbundle_user_profile
    from_email:
      address:        '%app.from_email_address%'
      sender_name:    '%app.from_email_name%'

simple_things_entity_audit:
    audited_entities:
        - AppBundle\Entity\Forsyningsvaerk
        - AppBundle\Entity\Bilag
        - AppBundle\Entity\Bygning
        - AppBundle\Entity\Configuration
        - AppBundle\Entity\Forsyningsvaerk
        - AppBundle\Entity\Rapport
        - AppBundle\Entity\VirksomhedRapport
        - AppBundle\Entity\Energiforsyning
        - AppBundle\Entity\Energiforsyning\InternProduktion
        - AppBundle\Entity\Pumpe
        - AppBundle\Entity\Solcelle
        - AppBundle\Entity\BelysningTiltag
        - AppBundle\Entity\BelysningTiltagDetail
        - AppBundle\Entity\KlimaskaermTiltag
        - AppBundle\Entity\KlimaskaermTiltagDetail
        - AppBundle\Entity\KoeleanlaegTiltag
        - AppBundle\Entity\KoeleanlaegTiltagDetail
        - AppBundle\Entity\PumpeTiltag
        - AppBundle\Entity\PumpeTiltagDetail
        - AppBundle\Entity\SolcelleTiltag
        - AppBundle\Entity\SolcelleTiltagDetail
        - AppBundle\Entity\SpecialTiltag
        - AppBundle\Entity\SpecialTiltagDetail
        - AppBundle\Entity\TekniskIsoleringTiltag
        - AppBundle\Entity\TekniskIsoleringTiltagDetail
        - AppBundle\Entity\TrykluftTiltag
        - AppBundle\Entity\TrykluftTiltagDetail
        - AppBundle\Entity\VarmeanlaegTiltag
        - AppBundle\Entity\VarmeanlaegTiltagDetail
        - AppBundle\Entity\VindueTiltag
        - AppBundle\Entity\VindueTiltagDetail
        - AppBundle\Entity\VentilationTiltag
        - AppBundle\Entity\VentilationTiltagDetail
        - AppBundle\Entity\Tiltag
        - AppBundle\Entity\TiltagDetail
        - AppBundle\Entity\Segment
        - AppBundle\Entity\TekniskIsoleringTiltagDetail\NyttiggjortVarme
        - AppBundle\Entity\Baseline
        - AppBundle\Entity\BaselineKorrektion

white_october_breadcrumbs:
  separator:

stof_doctrine_extensions:
    default_locale: en_US

    # Only used if you activated the Uploadable extension
    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path:       %kernel.root_dir%/../web/uploads

        # Mime type guesser class: Optional. By default, we provide an adapter for the one present in the HttpFoundation component of Symfony
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter

        # Default file info class implementing FileInfoInterface: Optional. By default we provide a class which is prepared to receive an UploadedFile instance.
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo

    orm:
        default:
            uploadable: true
            timestampable: true
            blameable: true

knp_snappy:
    pdf:
        enabled:    true
        options:    { page-size: A4, zoom: 1, footer-font-size: 8, header-font-name: 'Arial, Helvetica, sans-serif', header-font-size: 7, javascript-delay: 300, debug-javascript: true, margin-top: 25, margin-right: 0, margin-bottom: 20, margin-left: 0, header-spacing: 5, footer-spacing: 5 }

# https://twigexcelbundle.readthedocs.org/en/latest/installation.html#step-3-configure-the-bundle-optional
mewes_k_twig_excel:
    pre_calculate_formulas: false
    disk_caching_directory: "%kernel.cache_dir%/phpexcel"

app:
  pdf_export:
    base_url: %app.pdf_export.base_url%
    default_file_path: %app.pdf_export.default_file_path

trsteel_ckeditor:
    toolbar: ['document', 'clipboard', 'editing', 'insert', '/', 'styles', 'basicstyles', 'paragraph', 'links']
    toolbar_groups:
        document: ['Maximize','Source']
        clipboard: ['Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo']
        editing: ['Find','Replace','-','SelectAll']
        basicstyles: ['Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat']
        paragraph: ['NumberedList','BulletedList','-','Outdent','Indent','-','JustifyLeft', 'JustifyCenter','JustifyRight','JustifyBlock']
        links: ['Link','Unlink','Anchor']
        insert: ['Image', 'Table']
    contents_css: '/css/aaplus-manyone-pdfstyles.css'
    custom_config: '/js/ckeditor_config.js'
    filebrowser_image_browse_url:
        route: elfinder
        route_parameters:
            instance: default

fm_elfinder:
    #assets_path: / # default is /assets, this is where css/js elfinder files are
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, fm_tinymce, form, simple, custom
            #editor_template: custom template for your editor # default null
            #path_prefix: / # for setting custom assets path prefix, useful for non vhost configurations, i.e. http://127.0.0.1/mysite/
            #fullscreen: true|false # default is true, applies to simple and ckeditor editors
            #theme: smoothness # jquery theme, default is 'smoothness'
            include_assets: true # disable if you want to manage loading of javascript and css assets manually
            #visible_mime_types: ['image/png', 'image/jpg', 'image/jpeg'] # only show these mime types, defaults to show all
            connector:
                #debug: true|false # defaults to false
                roots:       # at least one root must be defined, defines root filemanager directories
                    uploads:
                        #show_hidden: true|false # defaults to false, hides dotfiles
                        driver: LocalFileSystem
                        path: uploads/content
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg', 'application/pdf']
                        upload_deny: ['all']
                        upload_max_size: 8M # also file upload sizes restricted in php.ini
                        #attributes: example of setting attributes permission
                        #    - { pattern: '/(.*?)/', read: true, write: false, locked: true }
